### PR TITLE
Some styling done to group page, more needed.

### PR DESCRIPTION
**Pull request by samanthamhill**
I need some help with getting the icon onto the page for the group and some help with understanding the side bar code so I can style it.

### CODE REVIEW

**Comment by CobeyH** [comment]
We should bring the icon text back on the group page back. We introduced that as a direct result of the user feedback because people were confused by the buttons with icons.

**Review by jpark052 — APPROVED** [review]
It looks great to me! I really like the giant group avatar icon we have in each group's page now

**Comment by CobeyH** [comment]
Wow, that rebase didn't go so well

**Comment by CobeyH** [comment]
After all that I still cannot rebase and merge.

**Pull request merged**
