### PR TITLE
Converting ride completion to use Charka Alert Dialog

### LINKED ISSUE #298: Completing ride should not bring up a browser alert
marking a ride as complete currently creates a browser alert, we should switch this to a chakra equivalent.

### PR DESCRIPTION
**Pull request by CobeyH**
Ride completion now uses a Charka-UI Alert Diolog instead of a react `success` component.
resolves #298

### CODE REVIEW

**Comment by MarcusDunn** [comment]
It doesn't seem to *do* anything. We should have some way for a user to tell if a ride is completed.

**Review by MarcusDunn — APPROVED** [review]

**Comment by CobeyH** [comment]
It's suppose to move it into the "Previous Rides" section. I thought I tested it and that functionality still works, but I'll double check

**Comment by CobeyH** [comment]
It seems to still work to me. The ride gets moved to the previous ride tab. I'm going to approve this and we can file a bug if you found an edgecase where it doesn't work.

**Comment by CobeyH** [comment]
image

**Pull request merged**
