### PR TITLE
Ride view card

### PR DESCRIPTION
**Pull request by doug-stormtree**
Not done, blocked on #55 but want to show initial version.

Expanding map refreshes on a hardcoded millisecond delay, if anyone knows how to synchronize this with the end of the animation that would be great. useLayoutEffect() fires too early.

### CODE REVIEW

**Comment by MarcusDunn** [comment]
I cannot see markers on mobile in the embedded ride view.

**Comment by doug-stormtree** [comment]
Map Refresh on Card Expand working with onAnimationComplete() event.

**Comment by doug-stormtree** [comment]
PR Ready for review.

**Review by CobeyH — APPROVED** [review]
Looks really good Doug! Such a big improvement

**Pull request merged**
