### PR TITLE
217 profile icons instead of pictures

### LINKED ISSUE #217: Profile Icons instead of pictures
Add a set of "default" icons that a user can choose from, (i.e. surfboard, fibre, basketball)

### PR DESCRIPTION
**Pull request by CobeyH**
Creating this on behalf on Sam since she is busy today. 
You can now use an Icon as a profile picture instead of uploading a picture. There is a search box to help users find the right icon for their use-case.

Resolves #217

### CODE REVIEW

**Comment by CobeyH** [comment]
There is an error in the console about using forward ref instead of ref on the icon buttons. That doesn't make sense to me since none of the buttons re-direct to a different page. Anybody have an idea what that's about?

**Comment by doug-stormtree** [comment]
Icon sizing and frame shape behaves weirdly on Safari only. Not sure why. I don't think it's essential that we fix all browser compatibility bugs at this stage.
image

**Comment by doug-stormtree** [comment]
I'm not seeing that error in my Chrome DevTools console when I load the icons selector. Can you post a screenshot or the full text?

**Comment by CobeyH** [comment]
I can't replicate the issue anymore either. I can check when I get home on my desktop computer where the error occurred yesterday. It didn't interfere with the functionality so I'm happy to ignore it for now and file a bug report when the find the condition to replicate the bug.

**Pull request merged**
