### PR TITLE
added leaving groups. Well tested.

### PR DESCRIPTION
**Pull request by MarcusDunn**
I squashed most of the really bad bugs. I'm certain there are more subtle ones - would gladly take a second pair of eyes to see if I missed anything.

### CODE REVIEW

**Comment by CobeyH** [comment]
I found some unexpected behaviour. If I'm in a group and I leave that group I'm not removed from the rides in that group.

**Comment by CobeyH** [comment]
Nitpicky issue, but you probably shouldn't remove passengers from `Previous Rides`.

**Review by CobeyH — COMMENTED** [review]
I joined a group, left that group, joined the group again and then tried to leave again. However, the "leave" button doesn't do anything the second time.

**Review by doug-stormtree — APPROVED** [review]
Looks good.

**Pull request merged**
