### PR TITLE
Custom Map Markers with Time

### LINKED ISSUE #349: Custom Map Icons with Time
* Feature name: Custom Map Icons
* Description: Replace the default map markers with ones that show the start, pickup, and destination times.
* Requires: None
* Status: In progress
* Time Estimation: <del>3 hours</del> 2 hours

**Additional context**
Example
image

### PR DESCRIPTION
**Pull request by doug-stormtree**
Will close #349.

Initial SVG Icon with time:
Screen Shot 2022-03-28 at 11 02 38 PM

Currently the start time is blank, and a different symbol will be used for the start. And the destination will be styled.

### CODE REVIEW

**Comment by doug-stormtree** [comment]
> I signed in and immediately got this error.
@CobeyH Okay, I believe I've dealt with the possible stale database entry issues.

**Review by CobeyH — COMMENTED** [review]
Looks like the rides created in the past are broken. Is this fixable or should we nuke the database? 
image

**Comment by CobeyH** [comment]
Additionally, this start point shows the lat/long it seems: 
image
And this endpoint is joinable: 
image

**Comment by doug-stormtree** [comment]
> Looks like the rides created in the past are broken. Is this fixable or should we nuke the database? image

So this only occurs in very old pre-routing rides, but adding a new pickup or changing the driver would fix them. I just didn't want to automatically regenerate the route because that could lead to an infinite loop if something was actually really broken with the ride. I could add even more fencing that display old markers in this case, but I just left it as not displaying markers if it fails my validation.

**Comment by CobeyH** [comment]
No worries then Doug. I'll add a pickup point to ever public group I can find to fix them

**Review by CobeyH — APPROVED** [review]
I went through and fixed every public ride I could find. I think this is good now!

**Comment by doug-stormtree** [comment]
Joining the Ride End was an issue I forgot to fix, that has been fixed now. I also replaced the fallback to LatLng with a getReverseGeocode request for that LatLng. A few extra MQ requests never hurt anyone.

I think it is good now.

**Pull request merged**
