### PR TITLE
Chat styling

### PR DESCRIPTION
**Pull request by CobeyH**
Moving the chat to the group drawer.
Refactoring the drawer to allow for future additions.
Restyling the chat.

### CODE REVIEW

**Comment by MarcusDunn** [comment]
image
not sure why, but this seems different (not floating right or left and doesn't take up full width) than what you sent me earlier (this is our shared chatting group)

**Review by doug-stormtree — CHANGES_REQUESTED** [review]
I can't track down the problem, but as Marcus noted the chat seems to tightly fit the length of the text or username and should fill the width of the input text box.

**Comment by CobeyH** [comment]
Oh yeah, that's my mistake. It's conforming to the width of the longest message. My test had long messages so i didn't see that. I'll fix that style issue

**Comment by CobeyH** [comment]
image
The shared chatting group is fixed.

**Review by doug-stormtree — APPROVED** [review]

**Pull request merged**
