### PR TITLE
split choosing dates into two components to makes less of a hassle.

### PR DESCRIPTION
**Pull request by MarcusDunn**
this should make it super clear what each thing does as well as allow for better time choosing components (I currently think it sucks less than before - but should suck less)

### CODE REVIEW

**Comment by CobeyH** [comment]
Could we have the date and time selection in the same step but different components? It seems a little excessive to have them in separate steps.

**Comment by MarcusDunn** [comment]
@CobeyH sure thing.

**Comment by MarcusDunn** [comment]
image

**Review by CobeyH — APPROVED** [review]
That looks great! Thanks for making that change for me.

**Pull request merged**
