### PR TITLE
Allowing default time

### LINKED ISSUE #399: Allow users to use default time
* Feature name: Default Time
* Description: When creating a ride, users shouldn't need to modify the time in order to press "next"
* Requires: Creating rides
* Status: Not started
* Time Estimation: 15 minutes.

**Additional context**
image

### PR DESCRIPTION
**Pull request by CobeyH**
Allow the user to proceed past the "start time" step in create ride using the default time.
Firefox doesn't have the small clock or calendar icons to the right of the input so I don't know how to fix the colour of those.
Resolves #399

### CODE REVIEW

**Comment by samanthamhill** [comment]
Looks good, can we remove the black icons instead of recolouring them?

**Comment by doug-stormtree** [comment]
> Looks good, can we remove the black icons instead of recolouring them?

I was curious about this so I did some research. If we add this to our css somewhere:
`::-webkit-calendar-picker-indicator {
  background-image: "none");
}`
Then both icons will be invisible, however it should be noted that on webkit (Chrome/Safari) the only place on the input that will bring up the actual Date or Time pickers is the last ~15% where these icons were.

**Comment by CobeyH** [comment]
Interesting. The way that date and time selection words across browsers is crazy. Can we merge this for now since it's a more important UX issue and we can look at that other issue afterwards?

**Review by doug-stormtree — APPROVED** [review]
Approved

**Pull request merged**
