### PR TITLE
Plan prices

### PR DESCRIPTION
**Pull request by CobeyH**
Using the price selector instead of a slider.

### CODE REVIEW

**Comment by MarcusDunn** [comment]
almost.

image

**Comment by CobeyH** [comment]
Sigh, okay. I'll investigate

**Comment by CobeyH** [comment]
Should be good now!

**Comment by jpark052** [comment]
Looks great! One thing that I'm wondering is, does it remember what the user selected? I have selected "enterprise" and clicked "save", then I opened up the setting again, and the focus was still on "free" tier

**Comment by MarcusDunn** [comment]
Looks good. Takes up a lot of screen real-estate on mobile. Perhaps remove the "gas calculator" and "optimized pickups" on smaller screens? I'll approve and leave up to you.

**Review by MarcusDunn — APPROVED** [review]

**Comment by CobeyH** [comment]
I don't understand your comment @MarcusDunn. The gas calculator is part of the ride card which I didn't touch.

**Comment by MarcusDunn** [comment]
Like to trim down the list of feature in the payment selection, perhaps just have the group size mentioned instead of all three.

**Comment by CobeyH** [comment]
Oh yeah, that's a good idea. Just on the group settings page though right? Not on the product page?

**Comment by MarcusDunn** [comment]
Think so.

**Comment by CobeyH** [comment]
Good suggestion @jpark052, I implemented persistent plans when opening the settings. It now shows you which plan you had selected previously.

**Comment by CobeyH** [comment]
I think I'm going to file the other issue you mentioned as a UX improvement for the future Marcus. I think we have bigger issues to fix right now.

**Pull request merged**
