### PR TITLE
Auto scroll chat

### PR DESCRIPTION
**Pull request by MarcusDunn**
I have no clue why scrollTo(0, 100000000) doesn't scroll to the bottom of the page. 

https://jsfiddle.net/re8sofpy/5/

this works fine.

but for whatever reason, this code does not.

I have spent an embarrassing amount of time on this.

It scrolls almost to the very bottom, but not quite. Any help is appreciated

### CODE REVIEW

**Comment by CobeyH** [comment]
Oh no, it scares me when Marcus can't solve an issue. I'll give it a try.

**Comment by MarcusDunn** [comment]
I think although can't imagine why, the fixed position chatbox may be doing something funky, but I couldn't find anything confirming my suspicions and the chat box should def be fixed.

**Comment by doug-stormtree** [comment]
The absolute positioning of the Input was the problem as the scrolling container was hidden beneath it.

I have set the DrawerBody to not scroll, and the ChatContents instead to scroll within VStack with ChatTextBox as sibling.

However, the scrollToBottom fires too early now (it works if I add a setTimeout). If @MarcusDunn knows how to fix this faster than I could then I leave it for you, or I will get back to it later tomorrow.

**Comment by CobeyH** [comment]
Marcus told me that he is going to ask people at work today and see if they know how to fix that.

**Comment by doug-stormtree** [comment]
Okay sweet. I think it's just a matter of passing the onAnimationComplete or some state that the animation is done down from the drawer to the ChatContents, that was probably handled automatically when the DrawerBody was scrolling.

Or having the scrollToBottom effect depend on when the messages state changes, but that might mean it would scroll down when someone else sends a message and you're reading old messages.

**Comment by MarcusDunn** [comment]
No dice with work. They suspected it's possibly realtime-db doing strange optimistic update things but couldn't offer a clean fix. I think leaving auto-scroll to languish and perhaps add a new-messages toast that when clicked scrolls to bottom may be a nice solution. Thoughts?

**Comment by doug-stormtree** [comment]
Okay no worries. I don't think it's a super essential feature but I will give it one more try with a few ideas I have in the next hour or so and if it doesn't work I think it's fine to merge.

**Comment by CobeyH** [comment]
What is the current state of this issue? Is anybody still working on it?

**Comment by MarcusDunn** [comment]
I'm happy to merge with the timeout hack.

**Comment by doug-stormtree** [comment]
I made the last changes so it doesn't seem right to review it as well, but I think it's ready to merge.

**Review by CobeyH — APPROVED** [review]
This looks much better than before!

**Pull request merged**
