### PR TITLE
Handing duplicate auth provider error

### LINKED ISSUE #276: Facebook registration handling already used email error
**Describe the bug**
When registering with facebook, if the user has already made an account with the email they use for facebook a silent error is thrown

**To Reproduce**
Log in with facebook that has same email as another account

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

### PR DESCRIPTION
**Pull request by CobeyH**
This should handle the error where you sign up with Google and then try to sign up with Facebook. Could somebody who has a Facebook account that is registered using a gmail address please test it? Such as @samanthamhill 
Resolves #276

### CODE REVIEW

**Comment by doug-stormtree** [comment]
I think that's a separate issue, I'll try to fix it right now. The ride-tandem.ca url has to be allowed for each auth method, and I'm assuming you are using that rather than the carpooling61... one based on the error?

**Comment by samanthamhill** [comment]
> I think that's a separate issue, I'll try to fix it right now. The ride-tandem.ca url has to be allowed for each auth method, and I'm assuming you are using that rather than the carpooling61... one based on the error?

I was using the link from this PR which is the carpool61 link, I'm not sure how to view the changes in the new version of the link for a PR.

**Comment by doug-stormtree** [comment]
Fascinating, it does seem to be an issue where that PR link hasn't been added as an auth domain, which is an automatic firebase thing. I manually added it but I don't know what could have caused that process to half-complete.

**Review by samanthamhill — APPROVED** [review]
Looks great! Toasts are very nice.
Screen Shot 2022-03-24 at 7 28 34 PM

**Pull request merged**
