### PR TITLE
Added checking for registration

### LINKED ISSUE #266: Registration button should be greyed when input is not valid
**Describe the bug**
Registration button should be greyed until user input valid information on all input fields

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

### PR DESCRIPTION
**Pull request by jpark052**
Added checking for registration inputs
full name should be at least 1 character
email should follow email format (e.g. * @ * . *)
password needs to be at least 6 characters

resolves #266

### CODE REVIEW

**Review by CobeyH — CHANGES_REQUESTED** [review]
Excellent addition. Could we possibly tell the user which input field is not filled in correctly and provide an error message? It's kind of frustrating UX to have no idea what's wrong with the input

**Comment by MarcusDunn** [comment]
lgtm

**Comment by jpark052** [comment]
Sounds good, will work on that!

**Comment by jpark052** [comment]
Added tooltip contents. The only concern is that when I wrapped up the button with the tooltip, it shrink the size of the button, but I figured I can worry about that once Sam's redesign is merged

**Review by CobeyH — APPROVED** [review]
Looks great!

**Pull request merged**
