### PR TITLE
Estimate Arrival Time

### LINKED ISSUE #219: Estimate Arrival time
We should estimate what time a trip will arrive at their destination.

### PR DESCRIPTION
**Pull request by doug-stormtree**
Closes #219

- Estimated trip duration stored in `routes/$rideId/duration` in seconds from MapQuest
- RideCard displays estimated arrival date and time calculated from start time
- If start and arrival are on the same day, hides the date from the arrival time row
- Changed Date and Time formatting to use Date().toLocaleString()

Looking for input if anyone thinks we should format the date strings differently, and if the arrival time should also be shown on the marker or as a clickable tooltip on the map.

Date and Time formatting should dynamically condense with app window size, I will look into this as well.

### CODE REVIEW

**Comment by CobeyH** [comment]
That's awesome! I'm really excited for this feature because I think it brings a lot more value to our application. If possible it would be great to have the pickup points display the time the ride will get there. That way the passengers will know when they will be picked up.

**Review by CobeyH — COMMENTED** [review]
Sorry, I should have made the above comment as a review comment so it would ping you.

**Review by samanthamhill — COMMENTED** [review]
By shown on the marker do you mean on the icon on the map or on the ride card? I agree with Cobey that the arrival time should be displayed somehow for each pickup point.

**Comment by jpark052** [comment]
I think displaying arrival time as a clickable tooltip would be find, if we already have that information on the ride card

**Comment by doug-stormtree** [comment]
> By shown on the marker do you mean on the icon on the map or on the ride card? 

I mean on the destination marker on the map, or in a tooltip similar to the pickup point tooltips (currently clicking on the destination marker does nothing)

> I agree with Cobey that the arrival time should be displayed somehow for each pickup point.

Yes, this is the next step, it's already under another issue so I am finishing this one first.

**Comment by samanthamhill** [comment]
> > By shown on the marker do you mean on the icon on the map or on the ride card?
> 
> I mean on the destination marker on the map, or in a tooltip similar to the pickup point tooltips (currently clicking on the destination marker does nothing)
> 
> > I agree with Cobey that the arrival time should be displayed somehow for each pickup point.
> 
> Yes, this is the next step, it's already under another issue so I am finishing this one first.

> I think it would look great if it was incorporated into the marker. That means that there is less moving parts visually on the map, a tool tip might be busy.  That being said, I think if we're going to put the pick up time on the ride card next to each pick up location the only markers that would need the time on them on the map is the start and the finish.

**Comment by doug-stormtree** [comment]
Sounds good, I will clean this up for merge, then do the pickup points issue, and then I'll create a third issue for new markers that display the times.

**Comment by CobeyH** [comment]
@doug-stormtree It doesn't look like a preview URL was generated or any checks were run. Am I missing something here?

**Comment by doug-stormtree** [comment]
> @doug-stormtree It doesn't look like a preview URL was generated or any checks were run. Am I missing something here?

@CobeyH I guess it doesn't run checks on drafts? I could have sworn it used to.

**Comment by CobeyH** [comment]
I've seen that issue once before on Jae's PR. Not sure why it happens occasionally

**Review by CobeyH — APPROVED** [review]
Looks good on both mobile and desktop using both long and short trips. Also tested pickup points and how that effects the end-time.

**Pull request merged**
