### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by CobeyH**
Login page UI only. It is not yet linked to Firebase

### CODE REVIEW

**Review by MarcusDunn — APPROVED** [review]
we should probably set up a eslint to enforce semicolons and " vs ' if not done already. Otherwise LGTM

**Review by jpark052 — APPROVED** [review]

**Review by jpark052 — APPROVED** [review]
Looks good to me as well

**Comment by doug-stormtree** [comment]
The build failed because of unused vars, should that check be disabled or do we want to fix those issues?

**Comment by CobeyH** [comment]
No reason to leave in unused variables. I will remove them.

**Pull request merged**
